name: C/C++ CI

on:
  push:
  pull_request:
    branches:
      - "main"
jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Generating CMakeFiles
        run: cmake -S . -B build -D BUILD_TESTS=ON
      - name: Building
        run: cmake --build build
      - name: Testing
        run: GTEST_COLOR=1 CTEST_OUTPUT_ON_FAILURE=1 ctest --test-dir build -V
  
  build-powerpc:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update apt 
        run: |
          sudo apt update
          sudo apt install g++-powerpc-linux-gnu
          sudo apt install gcc-powerpc-linux-gnu
          sudo apt install qemu-user-static
          sudo apt install libc6-powerpc-cross
      - name: Generating CMakeFiles
        run: >
          cmake -D CMAKE_TOOLCHAIN_FILE=TC-powerpc.cmake -S . -B build
          -D BUILD_TESTS=ON
      - name: Building
        run: cmake --build build
      - name: Testing
        run: GTEST_COLOR=1 CTEST_OUTPUT_ON_FAILURE=1 ctest --test-dir build -V