name: C/C++ CI

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed
jobs:
  build-amd64:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Building
        run: |
          cmake -S . -B build -D BUILD_TESTS=ON
          cmake --build build
      - name: Testing
        run: ctest --test-dir build
  
  build-powerpc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update apt 
        run: |
          sudo apt update
          sudo apt install g++-powerpc-linux-gnu
          sudo apt install qemu-user-static
          sudo apt install libc6-powerpc-cross
      - name: Building
        run: |
          cmake -S . -B build -D CMAKE_CXX_COMPILER=powerpc-linux-gnu-g++ -D BUILD_TESTS=ON -D CMAKE_LIBRARY_PATH_FLAG=/usr/powerpc-linux-gnu
          cmake --build build
      - name: Testing
        run: ctest --test-dir build
